-- MySQL Script generated by MySQL Workbench
-- Sun Aug 14 03:44:19 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`dueno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dueno` (
  `DNI` INT NULL,
  `nombre` VARCHAR(45) NULL,
  `Apellido` VARCHAR(45) NULL,
  `Telefono` VARCHAR(45) NULL,
  `Direccion` VARCHAR(45) NULL,
  PRIMARY KEY (`DNI`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`perro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`perro` (
  `ID_Perro` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Fecha_nac` VARCHAR(45) NULL,
  `Sexo` VARCHAR(45) NULL,
  `DNI_dueno` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_Perro`),
  CONSTRAINT `DNI_dueno`
    FOREIGN KEY ()
    REFERENCES `mydb`.`dueno` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Historial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Historial` (
  `ID_Historial` INT NOT NULL,
  `Fecha` VARCHAR(45) NULL,
  `Perro` VARCHAR(45) NULL,
  `Descripcion` VARCHAR(45) NULL,
  `Monto` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_Historial`),
  CONSTRAINT `Perro`
    FOREIGN KEY ()
    REFERENCES `mydb`.`perro` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO dueno( DNI, Nombre, Apellido, Telefono,Direccion ) VALUES
('28957346', 'Juan',  'Perez', '4789689',  'Belgrano 101'), 
('23546987',  'Maria',  'Perez', '4789689',  'Pueyrredon  811');

UPDATE dueno 
SET 
    Direccion = 'Libertad 123'
WHERE
    DNI = '28957346'
    